<h1 class="title">Welfare State Entry and Exit: Combatting macro-economic and life-course sustainability deficit in Europe</h1>
<h2 class="author">Data Analysis by Markus Kainu</h2>

-----


# Description

- Analysis are written in [R](http://r-project.org) and the outputs are generated using [knitr](http://yihui.name/knitr/)-package into simple html-files. 
- This page works as an index linking all the phases of the analysis together. Each page provide a time stamp at the top indicating the last time of generation. 
- A full version history is stored by the author. 
- There are **no data** within this site, only text & graphic outputs.


# General resources

- [Etherpad for collaborative writing](http://muuankarski.muistio.tieke.fi/EuSilcPanel2013)
- [Gesis: EU-silc documentation](http://www.gesis.org/en/services/data-analysis/official-microdata/european-microdata/eu-silc/eu-silc-further-information/)

# Data analysis

## Loading and cleaning the data

| html-page | source |
| --------- | ------ |
| [load and merge the datafiles](load_merge.html) | [source code](load_merge.Rmd) |
| [subsetting the data](subset.html) | [source code](subset.Rmd) |
| [diagnostics & missing data](missing.html) | [source code](missing.Rmd) |

## Descriptive statistics

| html-page | source |
| --------- | ------ |
| [Survival curves of mothers returning work](ds_survival_mothers.html) | [source code](ds_survival_mothers.Rmd) |


## Modelling the data


